version: "3.7"
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.27.8
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure
    environment:
      ENABLE_MODULES: text2vec-huggingface
      HUGGINGFACE_APIKEY: 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 
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'node1'
volumes:
  weaviate_data:
